language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.* DOCTRINE_ORM_VERSION=2.2.*
  - SYMFONY_VERSION=2.6.* DOCTRINE_ORM_VERSION=2.4.*
  - SYMFONY_VERSION=2.7.* DOCTRINE_ORM_VERSION=2.4.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require doctrine/orm:${DOCTRINE_ORM_VERSION} --no-update
  - composer update --dev

script: phpunit
